"""配置接口定义模块"""

from typing import Protocol


class ConfigLike(Protocol):
    @property
    def server_host(self) -> str: ...

    @property
    def server_port(self) -> int: ...

    @property
    def auth_token(self) -> str: ...

    @property
    def ws_path(self) -> str: ...

    @property
    def max_connections(self) -> int: ...

    @property
    def kick_old(self) -> bool: ...

    @property
    def resource_enabled(self) -> bool: ...

    @property
    def resource_host(self) -> str: ...

    @property
    def resource_port(self) -> int: ...

    @property
    def resource_path(self) -> str: ...

    @property
    def resource_dir(self) -> str: ...

    @property
    def resource_base_url(self) -> str: ...

    @property
    def resource_token(self) -> str: ...

    @property
    def resource_max_inline_bytes(self) -> int: ...

    @property
    def resource_ttl_seconds(self) -> int: ...

    @property
    def resource_max_total_bytes(self) -> int: ...

    @property
    def resource_max_files(self) -> int: ...

    @property
    def temp_dir(self) -> str: ...

    @property
    def temp_ttl_seconds(self) -> int: ...

    @property
    def temp_max_total_bytes(self) -> int: ...

    @property
    def temp_max_files(self) -> int: ...

    @property
    def enable_tts(self) -> bool: ...

    @property
    def tts_mode(self) -> str: ...

    @property
    def enable_streaming(self) -> bool: ...

    @property
    def cleanup_interval_seconds(self) -> int: ...
